gapic_generator_version: 2.40.1
protoc_version: '25.3'
googleapis_commitish: 6f289d775912966eb0cf04bda91e5e355c998d30
libraries_bom_version: 26.38.0
template_excludes:
  - '.kokoro/nightly/integration.cfg'
  - '.kokoro/nightly/java11-integration.cfg'
  - '.kokoro/nightly/samples.cfg'
  - '.kokoro/presubmit/integration.cfg'
  - '.kokoro/presubmit/samples.cfg'
  - '.kokoro/presubmit/graalvm-native.cfg'
  - '.kokoro/presubmit/graalvm-native-17.cfg'
  - '.kokoro/requirements.in'
  - '.kokoro/requirements.txt'
  - '.github/trusted-contribution.yml'
  - '.github/workflows/auto-release.yaml'
  - 'CONTRIBUTING.md'
  - 'renovate.json'
libraries:
  - api_shortname: "storage"
    name_pretty: "Cloud Storage"
    product_documentation: "https://cloud.google.com/storage"
    client_documentation: "https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/history"
    api_description: "is a durable and highly available object storage service. Google Cloud Storage is almost infinitely scalable and guarantees consistency: when a write succeeds, the latest copy of the object will be returned to any GET, globally."
    issue_tracker: "https://issuetracker.google.com/savedsearches/559782"
    release_level: "stable"
    language: "java"
    repo: "googleapis/java-storage"
    repo_short: "java-storage"
    distribution_name: "com.google.cloud:google-cloud-storage"
    codeowner_team: "@googleapis/cloud-storage-dpe"
    api_id: "storage.googleapis.com"
    requires_billing: true
    library_type: "GAPIC_COMBO"
    extra_versioned_modules: "gapic-google-cloud-storage-v2"
    excluded_poms: "google-cloud-storage-bom,google-cloud-storage"
    recommended_package: "com.google.cloud.storage"
    GAPICs:
      - proto_path: google/storage/v2
      - proto_path: google/storage/control/v2
